name: Build

on: push

jobs:
  build_check_job:
    name: Assemble Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble Dubug
        run: ./gradlew assembleDebug